name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ hello.c
    - name: test 1
      run: ./a.out
    - name: test 2
      run: ./a.out
    - name: test 3
      run: ./a.out
